<a href="https://colab.research.google.com/github/tyleresong/mis433/blob/main/assignment_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [6]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Tyler Song
Welcome, Tyler Song!


In [7]:
# complete your program here
f = float(input('Please enter the temperature in Fahrenheit: '))

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140.0
140.0F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [8]:
# complete your program here
c = float(input('Please enter the temperature in Celcius: '))

print(c)

f = c * 9/5 + 32

print(f'{c}C is {f} in Fahrenheit. ')

Please enter the temperature in Celcius: 60
60.0
60.0C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [9]:
# complete your program here
d = float(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? ')

print(d)
print(m)

if(m == 'C'):
    f = d * 9/5 + 32
    print(f'{d}C is {f} in Fahrenheit')
elif(m == 'F'):
    c = (d - 32) * 5/9
    print(f'{d}F is {c} in Celsius')

Please enter the temperature: 140
Is this in Celsius or Fahrenheit? F
140.0
F
140.0F is 60.0 in Celsius


## Question 2

Have some fun with strings.

In [10]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [11]:
# Find the length of this sentence.
print(len(sentence))


48


In [12]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [13]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[10:-10])

eap. Show me the code - Linu


In [14]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split(' '))

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [15]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().replace('.','').replace("-","").split(" "))

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', '', 'linus', 'torvalds']


In [16]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
for v in vowels:
    print(v, sentence.count(v))

a 3
e 4
i 2
o 3
u 1


In [17]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
    if sentence[i] in vowels:
        print(i)


1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [18]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
count = 0
for i in range(5):
    cubes.append(i**3)
    count += 1
print(cubes)


[0, 1, 8, 27, 64]


In [19]:
# Use list comprehension to create the same list
new_List = [i**3 for i in range(5)]
print(new_List)

[0, 1, 8, 27, 64]


In [20]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
vowels = ['a', 'e', 'i', 'o', 'u']
vowels = 'aeiou'
new_List = [i for i in range(len(sentence)) if sentence[i] in vowels]
print(new_List)


[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [21]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = float(input('How many numbers do you want?: '))

# add your code here
count = 0
for i in range(int(n)):
   if i <= 1:
       fibonacci.append(i)
   else:
       fibonacci.append(fibonacci[i-2] + fibonacci[i-1])
print(fibonacci)



How many numbers do you want?: 5
[0, 1, 1, 2, 3]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [22]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'95%': '0.95'}
print(v_dict['95%'])

0.95


In [23]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v)
v_dict = {'Pfizer': '95%', 'Moderna': '95%', 'AstraZeneca': '72%', 'Johnson & Johnson': '66%'}
print(v_dict[v])


Which vaccine? Pfizer
Pfizer
95%


In [24]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = '91.4%'
print(v_dict)

{'Pfizer': '95%', 'Moderna': '95%', 'AstraZeneca': '72%', 'Johnson & Johnson': '66%', 'Sputnik V': '91.4%'}


In [25]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = '50.38%'
print(v_dict)

{'Pfizer': '95%', 'Moderna': '95%', 'AstraZeneca': '72%', 'Johnson & Johnson': '66%', 'Sputnik V': '91.4%', 'Sinovac': '50.38%'}


In [26]:
# Print vaccines with efficacy lower than 90%
for v in v_dict:
  if v_dict[v] < '90%':
    print(v)



AstraZeneca
Johnson & Johnson
Sinovac


In [27]:
# delete the Sinovac vaccine from the dictionary.
del v_dict['Sinovac']
print(v_dict)

{'Pfizer': '95%', 'Moderna': '95%', 'AstraZeneca': '72%', 'Johnson & Johnson': '66%', 'Sputnik V': '91.4%'}


In [28]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here

alphabet = 'abcdefghijklmnopqrstuvwxyz'
for ch in alphabet:
  ch_dict[ch] = sentence.count(ch)

# print the dictionary
print(ch_dict)

{'a': 1, 'b': 1, 'c': 1, 'd': 1, 'e': 3, 'f': 1, 'g': 1, 'h': 2, 'i': 1, 'j': 1, 'k': 1, 'l': 1, 'm': 1, 'n': 1, 'o': 4, 'p': 1, 'q': 1, 'r': 2, 's': 1, 't': 2, 'u': 2, 'v': 1, 'w': 1, 'x': 1, 'y': 1, 'z': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [29]:
import numpy as np

In [30]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([range(2,40,2)])

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38]])

In [31]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([range(1,40,2)])

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39]])

In [32]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.array(range(100)).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1, (10, 10))
M = np.random.normal(0,1, (10, 10))
M.shape


(10, 10)

In [34]:
# Count the numbers in M with an absolute value greater than 1.
count = 0
for i in range(10):
  for j in range (10):
    if abs(M[i][j]) > 1:
      count += 1
print(count)

33


In [35]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (int(r), int(c)))
arr

Row count: 8
column count: 8


array([[10, 18, 14, 18, 13, 14, 12, 11],
       [13, 15, 17, 13, 16, 17, 14, 12],
       [17, 18, 16, 15, 18, 16, 13, 15],
       [19, 12, 11, 17, 14, 10, 14, 12],
       [12, 18, 13, 15, 15, 10, 11, 12],
       [16, 16, 18, 18, 14, 15, 14, 15],
       [13, 17, 18, 15, 11, 10, 13, 14],
       [19, 19, 15, 18, 10, 10, 16, 19]])

In [36]:
# output the element in the first row and the third column
arr[0, 2]

np.int64(14)

In [37]:
# output the element in the second row and the last column
arr[1, -1]

np.int64(12)

In [38]:
# output the second row of the array
arr[1]

array([13, 15, 17, 13, 16, 17, 14, 12])

In [39]:
# output the second last row of the array
arr[-2]

array([13, 17, 18, 15, 11, 10, 13, 14])

In [40]:
# output the second column of the array
arr[:, 1]

array([18, 15, 18, 12, 18, 16, 17, 19])

In [41]:
# output the second last column of the array
arr[:, -2]

array([12, 14, 13, 14, 11, 14, 13, 16])

In [42]:
# output the upper-left 3x3 sub-array
u = arr[0:3, 0:3]
u

array([[10, 18, 14],
       [13, 15, 17],
       [17, 18, 16]])

In [43]:
# output the bottom-left 3x3 sub-array
b = arr[-3:, 0:3]
b

array([[16, 16, 18],
       [13, 17, 18],
       [19, 19, 15]])

In [44]:
# output the upper-right 3x3 sub-array
ur = arr[0:3, -3:]
ur

array([[14, 12, 11],
       [17, 14, 12],
       [16, 13, 15]])

In [45]:
# output the bottom-right 3x3 sub-array
br = arr[-3:, -3:]
br

array([[15, 14, 15],
       [10, 13, 14],
       [10, 16, 19]])

In [46]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.array(range(1,51))
A
# Reshape A to a 5x10 array in the following format:
AR = A.reshape(5,10)
AR
# first row: [1,...,10]
AR[0]
# second row: [11,...,20]
AR[1]
# fifth row: [41,...,50]
AR[4]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [47]:
# add a row [51,...,60] to A
AR = np.append(AR, [range(51,61)], axis=0)
AR

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [48]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1 = AR[:3]
A2 = AR[3:]
print(A1)
print(A2)


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [49]:
# Add 10 to each element of A
AR = AR + 10
AR

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [50]:
# Calculate the square root of each element in A
AR = np.sqrt(AR)
AR

array([[3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669],
       [7.81024968, 7.87400787, 7.93725393, 8.        , 8.06225775,
        8.1240384 , 8.18535277, 8.24621125, 8.30662386, 8.36660027]])

In [51]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1, (10, 10))
M = np.random.normal(0,1, (10, 10))
M.shape

(10, 10)

In [52]:
# Print the mean, standard devietion of all numbers in M
mean = np.mean(M)
print(mean)
std = np.std(M)
print(std)

-0.08949822604884546
0.96034295159682


In [53]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
max = np.max(M)
print(max)
third_quartile = np.percentile(M, 75)
print(third_quartile)
median = np.median(M)
print(median)
first_quartile = np.percentile(M, 25)
print(first_quartile)

2.3827951431599415
0.5839169633898016
-0.08944851614621194
-0.7537576577962557
