<a href="https://colab.research.google.com/github/tyleresong/mis433/blob/main/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python

In this course, we will use the Python programming language for all tutorials, exercises, and assignments.

Python is a great general-purpose programming language. With the help of several popular libraries (e.g., numpy, scipy, pandas, matplotlib, sklearn), it provides a powerful environment for data analytics and computing.

It'd be great if you have some experience with Python and numpy. If not, we will take this notebook as a crash course on basics for Python programming and its use for scientific computing.

Many say that Python code is like pseudocode for it can express very powerful ideas in very few lines of code while being very readable.

As an example, here is an implementation of the classic quicksort algorithm in Python:

In [ ]:
# Define a fuction named "quicksort" that takes an array "arr" as input
def quicksort(arr):
    # check if the array is empty
    if len(arr) <= 1:
        return arr
    # find the element in the middle of the of array
    pivot = arr[len(arr) // 2]
    # save all elements less than the pivot in an list called "left"
    left = [x for x in arr if x < pivot]
    # save all elements equal to the pivot in an list called "middle"
    middle = [x for x in arr if x == pivot]
    # save all elements greater than the pivot in an list called "right"
    right = [x for x in arr if x > pivot]
    # combine left + middle + right together
    # notice that this quicksort function is recurisive: it calls itself.
    return quicksort(left) + middle + quicksort(right)

'''
You can call this function to sort a list of numbers.
You can also use this function to sort a list of strings.

BTW. Here I show another way of commenting multiple lines in Python code.
'''
print(quicksort([3,8,16,9,14,8,10,1,2,19]))
print(quicksort(['Google','Apple','Microsoft','Amazon']))

[1, 2, 3, 8, 8, 9, 10, 14, 16, 19]
['Amazon', 'Apple', 'Google', 'Microsoft']


## Basic Data Types

Like most languages, Python has a number of basic types including integers, floats, booleans, and strings.

**Numbers**: Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

<class 'int'>
3
4
2
6
9


In [ ]:
x = x + 1  # Assign the value (x+1) to x
x

4

In [ ]:
x += 1     # This is simpler.
x

5

In [ ]:
x *= 2     # Assign the vlaue (x*2) to x
x

10

In [ ]:
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints multiple items together

<class 'float'>
2.5 3.5 5.0 6.25


In [ ]:
# Exercise:
# In a case, there are c chickens and r rabbits. How many heads and legs are there in total?
c = input('How many chickens?')
r = input('How many rabbits?')

c = int(c)
r = int(r)

# head count:
print(f"Head count: {c + r}")

# leg count:
print(f"Leg count: {2 * c + 4 * r}")

How many chickens?6
How many rabbits?7
Head count: 13
Leg count: 40


**Booleans**: Python implements all of the usual operators for Boolean logic:

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"

In [ ]:
x=20

In [ ]:
x = x - 9
if x > 3:
    print(str(x) + ' is greater than 3.')

11 is greater than 3.


In [ ]:
# Exercise:
# Are there more chickens than rabbits? Print out your conclusion.
if c > r:
    print('There are more chickens than rabbits.')
else:
    print('There are more rabbits than chickens.')

There are more rabbits than chickens.


**Strings**: Python has great support for strings:

In [ ]:
h = 'hello'    # String literals can use single quotes
w = "world"    # or double quotes; it does not matter.
print(h)
print(len(h))  # len() returns the string length
hw = h + ' ' + w  # String concatenation
print(hw)
hwy = '%s %s %d' % (h, w, 2021)  # string formatting
print(hwy)

String objects have a bunch of useful methods:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print('Hello'.lower()) # Convert a string to lowercase; prints "hello"
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

In [ ]:
# More functions/operaitons for strings
chords = 'C G Am Em F C Dm G'
print(chords.split()) # Split a string to a list of strings, default by ' '

print(chords.replace(' ','-').split('-')) # Split a string by '-'

['C', 'G', 'Am', 'Em', 'F', 'C', 'Dm', 'G']
['C', 'G', 'Am', 'Em', 'F', 'C', 'Dm', 'G']


How to extract a substring from a string? You can use the following templates:
- ``string[start:end]``: Get all characters from index start to end-1
- ``string[:end]``: Get all characters from the beginning of the string to end-1
- ``string[start:]``: Get all characters from index start to the end of the string
- ``string[start:end:step]``: Get all characters from start to end-1 discounting every step character

In [ ]:
print(len(chords)) # The length of a string

# substrings
print(chords[0]) # The first character
print(chords[0:3]) # The first three characters
print(chords[:3]) # The first three characters
print(chords[5:10]) # The characters from index 5 to 9
print(chords[-4]) # The 4th characters from the end
print(chords[-4:]) # The last four characters

18
C
C G
C G
m Em 
D
Dm G


Count the occurrence of a character in a string.

For example, count the occurrence of spaces (' ') in the string.

In [ ]:
for i in range(len(chords)):
  print(i, chords[i])



0 C
1  
2 G
3  
4 A
5 m
6  
7 E
8 m
9  
10 F
11  
12 C
13  
14 D
15 m
16  
17 G


In [ ]:
# Using a loop
count = 0
for i in range(len(chords)):
    if chords[i] == ' ':
        count += 1
count

7

In [ ]:
# You can also iterate all characters in string like this:
count = 0
for ch in chords:
    if ch == ' ':
        count += 1
count

7

In [ ]:
# Using count()
chords.count(' ')

7

In [ ]:
# Exercise:
# Given the following string:
line = "My mama always said life was like a box of chocolates. You never know what you're gonna get."

# Find the number of characters:
print(len(line))

# Print the substring "box" using indices"


# Split this string into a list of words, all in lower case, without puncutations.
# Note: split "you're" into "you" and "re"
print(line.lower().replace("."," ").replace("'"," ").split())

92
['my', 'mama', 'always', 'said', 'life', 'was', 'like', 'a', 'box', 'of', 'chocolates', 'you', 'never', 'know', 'what', 'you', 're', 'gonna', 'get']


# Python List

See https://realpython.com/python-lists-tuples/

A Python list is a collection of arbitrary objects, similar to an array in many other programming languages.

- Lists are ordered.
- Lists can contain any arbitrary objects.
- List elements can be accessed by index.
- Lists can be nested to arbitrary depth.

In [ ]:
# one dimensional list/array
a = ['apple', 'orange', 'kiwi', 'grape', 'cherry']
print(a[4])
print(a[1:3])
print(a[:3])
print(a[2:])
print(a[:-2])
print(a[1:-2])

cherry
['orange', 'kiwi']
['apple', 'orange', 'kiwi']
['kiwi', 'grape', 'cherry']
['apple', 'orange', 'kiwi']
['orange', 'kiwi']


In [ ]:
# nested list/two dimentional array
b = [['apple', 2], ['orange', 5], ['kiwi', 4], ['grape', 3], ['cherry', 25]]
# show the quantity of kiwi
print(b[2][1])

4


In [ ]:
# make sure you know the following list methods
c = a.append('peach')
print(c) # NOTE that append() change a list in place and does not return a new list
print(a)
a.remove('kiwi')
print(a)

None
['apple', 'orange', 'kiwi', 'grape', 'cherry', 'peach']
['apple', 'orange', 'grape', 'cherry', 'peach']


### List Comprehension
List comprehension formula:

``new_list = [expression (if conditional for changing the value) for member in iterable (if conditional for filtering the value)]``

In [ ]:
d = [5, -2, 7, 3, -4, 10]
d

[5, -2, 7, 3, -4, 10]

In [ ]:
dl = []
for i in d:
  if i<9:
    if i>0:
      dl.append("p")
    else:
      dl.append("n")
print(dl)

['p', 'n', 'p', 'p', 'n']


In [ ]:
d = [5, -2, 7, 3, -4, 10]

# create a list by replacing each number that is smaller than 9 with 'p' if positive, and 'n' if negative
d_new = ['p' if i > 0 else 'n' for i in d if i <9]
print(d_new)

['p', 'n', 'p', 'p', 'n']


In [ ]:
# iterate over a list via list comprehension
[print(i) for i in d]

5
-2
7
3
-4
10


[None, None, None, None, None, None]

In [ ]:
# another way
for i in d:
    print(i)

5
-2
7
3
-4
10


In [ ]:
# check out f strings: https://realpython.com/python-f-strings/
# if you want to get the index

for i in range(len(d)):
    print(f'the number at index of {i} is {d[i]}')

the number at index of 0 is 5
the number at index of 1 is -2
the number at index of 2 is 7
the number at index of 3 is 3
the number at index of 4 is -4
the number at index of 5 is 10


In [ ]:
# Exercise:

# Given the following string:
line = "My mama always said life was like a box of chocolates. You never know what you're gonna get."

# Split this string into a list of words, all in lower case, without puncutations.
# Note: split "you're" into "you" and "re"


# Create a new list of words with at least four characters.


## Python Dictionary

A dictionary stores (key, value) pairs.

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

It is easy to iterate over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs.' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs.
A cat has 4 legs.
A spider has 8 legs.


In [ ]:
d["rocky"] = 5
d

{'person': 2, 'cat': 4, 'spider': 8, 'rocky': 5}

In [ ]:
for a in d:
  if d[a]>=5:
    print(f"A {a} has {d[a]}")

A spider has 8
A rocky has 5


In [ ]:
# Exercise:
# Given the following string:
line = "My mama always said life was like a box of chocolates. You never know what you're gonna get."

# Crete a dictionary to store the start index of each word.
# e.g., {'my':0, 'mama':3, ...}


## Python Set

Unlike a list, a set is an *unordered* collection of distinct elements.

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


## Python Tuple
A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [ ]:
t = ('foo', 'bar', 'baz', 'qux', 'quux', 'corge')
print(t[0])
print(t[-1])

foo
corge


Tuples can be used as keys in dictionaries and as elements of sets.

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
print(d)
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Given a key (5, 6), find the corresponding value in dictionary d.

# Numpy Basics

Referece Chapter: https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html

- NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.
- NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python.

In [ ]:
import numpy as np
np.__version__

'2.0.2'

Creating Arrays from Python Lists

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

All elements in a NumPy array must be of the same type. If types do not match, NumPy will upcast if possible: integers are up-cast to floating point:

In [ ]:
# up-cast
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
# explicit data type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# nested lists result in multi-dimensional arrays
np.array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0 (inclusive), ending at 20 (exlusive), stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Create an array of five values evenly spaced between 0 and 10
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.46595386, 0.54098152, 0.27364463],
       [0.40916921, 0.48111651, 0.93831532],
       [0.17637101, 0.9849742 , 0.89247764]])

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.6818055 ,  1.03893719,  0.1181436 ],
       [-0.51352255,  1.08657721, -1.73472132],
       [-2.41810467, -1.57703224,  1.17519916]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[8, 4, 7],
       [7, 8, 1],
       [3, 7, 5]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

In [ ]:
np.random.seed(42)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array: 3 rows x 4 columns
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array: 3 4 rows x 5 columns two-dimentional array

print(x1)
print("********")
print(x2)
print("********")
print(x3)

[6 3 7 4 6 9]
********
[[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
********
[[[5 1 4 0 9]
  [5 8 0 9 2]
  [6 3 8 2 4]
  [2 6 4 8 6]]

 [[1 3 8 1 9]
  [8 9 4 1 3]
  [6 7 2 0 3]
  [1 7 3 1 5]]

 [[5 9 3 5 1]
  [9 1 9 3 7]
  [6 8 7 4 1]
  [4 7 9 8 8]]]


In [ ]:
print(f'x3 ndim: {x3.ndim}')
print(f'x3 shape: {x3.shape}')
print(f'x3 size: {x3.size}')

In [ ]:
print("dtype:", x3.dtype)

# Numpy Array Indexing and Slicing

To access a slice of an array x, use this:

``x[start:stop:step]``

The slice extends from the ‘start’ index and ends one item before the ‘stop’ index.

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1.

In [ ]:
# you need to understand the following
print(x1[4])
print(x2[2, 0])
print(x2[2, :])
print(x1[::-1]) # all elements reversed

In [ ]:
print(x3[2]) # The element of index=2 in x3 which is a 4x5 array; same as x3[2,:]

In [ ]:
print(x3[2, 2, 4]) # third 4x5 array, row 3 and column 5, which gives you 5
print(x3[2, 1:4, 4]) # think what this is trying to do

### Numpy slices are views of the array - not copies!!

This default behavior of Numpy is very useful: when we handle large datasets, this allows us to access and process part of the datasset without making copies of the underlying data (could be slow and costly).

In [ ]:
# slices of a list are copies of the list
# changing slices does not change the list
a = [1, 2, 3, 4, 5]
b = a[2:4]
print(b)
b[1] = 9
print(b)
print(a)

In [ ]:
# slices of a Numpy array are views of the array
# changing the slices will change the original array!!!
c = np.array([1, 2, 3, 4, 5])
#d = c[2] # note c[2] is not a slice of c, if you want to have one element as a slice use c[2:3]
d = c[2:4]
print(d)
d[1] = 9
print(d)
print(c)

NameError: name 'np' is not defined

If you want to make a copy of the slice, you have to use the copy() method:

In [ ]:
# c won't change
e = c[2:4].copy()
print(e)
e[1] = 8
print(e)
print(c)

# Other Useful Methods

- ``sort()``, ``argsort()``
- ``reshape()``
- ``concatenate()``
- ``split()``, ``vsplit()``: split arrays vertically or horizontally
- ``vstack()``, ``hstack()``: stacking arrays vertically or horizontally

In [ ]:
# sorting

a = np.array([2, 5, 4, 8, 3])
b = np.sort(a)
print(f'b is {b}')
print(f'a is not changed: {a}')
c = np.argsort(a) # argsort() returns the indexes of the sorted array
print(f'c is the indexes of the sorted a: {c}')
a.sort() # sorting in place, a is changed
print(f'a has been changed: {a}')

In [ ]:
# reshaping
a = np.arange(1, 10)
print(f'a is a simple one dimensional array: {a}')
grid = a.reshape((3, 3))
print(f'a becomes a 3x3 grid after reshaping:')
print(grid)

In [ ]:
# Concatenation of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x, y]))

# + for numpy is sum, not concatenation
z = x + y
print(z)

# list is different, + is concatenation
a = [1, 2]
b = [3, 4]
print(a + b)

## axis

axis 0 means row (default), axis 1 means column

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis (row), default
np.concatenate([grid, grid], axis=0)

In [ ]:
# concatenate along the second axis (column) (zero-indexed)
np.concatenate([grid, grid], axis=1)

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

In [ ]:
# splitting arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2 = np.split(x, [3])
print(x1, x2)

In [ ]:
# splitting arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 6])
print(x1, x2, x3)

In [ ]:
# split vertically
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

## Computation on Arrays

In [ ]:
x = np.arange(5)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

In [ ]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

## NumPy functions

These arithmetic operations are convenient wrappers around specific functions built into NumPy. The following table lists the arithmetic operators implemented in NumPy:

- ``+``:	``np.add``	Addition
- ``-``:	``np.subtract``	Subtraction
- ``-``:	``np.negative``	Unary negation
- ``*``:	``np.multiply``	Multiplication
- ``/``:	``np.divide``	Division
- ``//``:	``np.floor_divide``	Floor division
- ``**``:	``np.power``	Exponentiation
- ``%``:	``np.mod``	Modulus/remainder

In [ ]:
np.add(x,2)

In [ ]:
# Absolute value
x = np.array([-2, -1, 0, 1, 2])
abs(x)

In [ ]:
np.absolute(x)

In [ ]:
np.abs(x)

In [ ]:
# Exponents
x = [1, 2, 3, 4, 5]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

In [ ]:
# Logorithms
x = [1, 2, 4, 10, 100]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

## Aggregation functions

Aggregates available in NumPy can be extremely useful for summarizing a set of values.

As a simple example, let's consider the heights (cm) of US presidents.

In [ ]:
heights_cm = [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173,
              174, 183, 183, 168, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183,
              177, 185, 188, 188, 182, 185, 190, 183]
heights = np.array(heights_cm)
print(heights)

In [ ]:
print("Mean height:       ", heights.mean())
print("Standard deviation:", heights.std())
print("Minimum height:    ", heights.min())
print("Maximum height:    ", heights.max())

In [ ]:
print("25th percentile:   ", np.percentile(heights, 25))
print("Median:            ", np.median(heights))
print("75th percentile:   ", np.percentile(heights, 75))